### ISSUE TITLE
Faraday Parse Error

### ISSUE THREAD

**Issue by devinfoley** [kern/zeppelin#15]
When I call client.push, I get a notification on my phone, but a Faraday::Error:ParsingError gets thrown. Ever seen this?

I should note I'm using faraday 0.8.4 and faraday_middlewear 0.8.8.

Thanks!

**Comment by jherdman** [comment]
I can't say that I've seen this happen before. Perhaps it's something regarding the response that you're receiving. Could you paste in the raw response body if possible?

**Comment by devinfoley** [comment]
I'm unable to see the raw response body because the error gets thrown before I can assign the response to a variable. I can see though that the exception message is **757: unexpected token at 'null'** if that helps. Coming from _gems/json-1.7.5/lib/json/common.rb:155:in `parse'"_.

Maybe I'm using an incompatible version of the JSON gem?

**Comment by jherdman** [comment]
Oh... Now that is quite interesting. It sounds like you're easily reproducing this though. To clarify, are you seeing the request successfully send, or is this happening during the response? The JSON you're sending may be invalid. You may want to try something like the following to test:

``` ruby
> require 'json'
> JSON.dump(request_hash)
```

If you see an error here, your payload needs to be reevaluated. If not, then we need to start coming up with a way to check the response :)

**Comment by jherdman** [comment]
Has your issue been resolved?

**Comment by bartiaco** [comment]
I'm actually getting the same error in my resque jobs after updating zeppelin to 0.8.2, faraday 0.8.4, and     faraday_middleware 0.8.8.  Except that I'm using the batch push method.

It appears to be blowing up when it processes the response. As a sidenote, this was working prior to the gem update, and I'd really like to be able to work with the newer version of faraday, as I have other gems that want it.

Here's the relevant stack trace from newrelic:

``` ruby
…d/bundle/ruby/1.9.1/gems/json-1.6.6/lib/json/common.rb: 148:in `parse'
…d/bundle/ruby/1.9.1/gems/json-1.6.6/lib/json/common.rb: 148:in `parse'
…re-0.8.8/lib/faraday_middleware/response/parse_json.rb:  11:in `block in <class:ParseJson>'
…re-0.8.8/lib/faraday_middleware/response_middleware.rb:  48:in `call'
…re-0.8.8/lib/faraday_middleware/response_middleware.rb:  48:in `parse'
…re-0.8.8/lib/faraday_middleware/response_middleware.rb:  39:in `process_response'
…re-0.8.8/lib/faraday_middleware/response_middleware.rb:  32:in `block in call'
…/ruby/1.9.1/gems/faraday-0.8.4/lib/faraday/response.rb:  63:in `on_complete'
…re-0.8.8/lib/faraday_middleware/response_middleware.rb:  30:in `call'
…re-0.8.8/lib/faraday_middleware/request/encode_json.rb:  23:in `call'
…uby/1.9.1/gems/faraday-0.8.4/lib/faraday/connection.rb: 226:in `run_request'
…uby/1.9.1/gems/faraday-0.8.4/lib/faraday/connection.rb:  99:in `post'
…/bundle/ruby/1.9.1/gems/zeppelin-0.8.2/lib/zeppelin.rb: 349:in `post_request'
…/bundle/ruby/1.9.1/gems/zeppelin-0.8.2/lib/zeppelin.rb: 196:in `batch_push'
```

any suggestions?

**Comment by jherdman** [comment]
Hm. This is looking like an issue within the Faraday Middleware gem. The line in Zeppelin wherein the problem arises merely [passes a message down](https://github.com/CapnKernul/zeppelin/blob/develop/lib/zeppelin.rb#L349) to Faraday with the associated middleware. You may want to post this issue there.

**Comment by bartiaco** [comment]
I actually finally figured this out.  The problem is twofold.

Faraday switched to the standard ruby JSON library.  The problem is that the JSON parser is more picky than multijson.  The key difference, if you try to parse the invalid json string "null", multijson returns nil, but JSON throws this exception.

For us, this coincided with an Urban Airship bug where their api was incorrectly returning a string of "null" instead of a valid json response for several days.

It's hard to say if this is something that zeppelin should rescue.
