### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by diginess** [kern/zeppelin#6]
I get this error OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

It is related to the Faraday gem: 
http://stackoverflow.com/questions/3977303/omniauth-facebook-certificate-verify-failed/5512518#5512518

It could be useful to add a "ca_path" param to the initializer.

**Comment by kern** [comment]
This is now in v0.4.0.
